sqlite3:
  adapter: sqlite3
  database: usda_nutrient_database.sqlite3

mysql:
  adapter: mysql2
  hostname: localhost
  username: root
  password:
  database: usda_nutrient_database
  charset: utf8

postgresql:
  adapter: postgresql
  hostname: localhost
  username: postgres
  password:
  database: usda_nutrient_database
  encoding: utf8
